# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-09 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sus',
            name='q1',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم این سیستم را به طور مکرر استفاده خواهم نمود'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q10',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم که باید با خیلی از ابزارها قبل از استفاده از سیستم اشنایی داشته باشم'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q2',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم این سیستم بی خودی پیچیده است و می تواند ساده تر باشد'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q3',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم استفاده از این سیستم ساده است'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q4',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم کارکردن با این سیستم نیازمند یک متخصص می باشد'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q5',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم قابلیت های مختلف در این سیستم به خوبی فراهم شده است'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q6',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم  دراین سیستم سازگاری زیادی وجود ندارد'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q7',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم که افراد کار با این سیستم را سریعا یاد می گیرند'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q8',
            field=models.FloatField(default=3, verbose_name='من فکر می کنم که استفاده از این سیستم سنگین و طاقت فرسا است'),
        ),
        migrations.AddField(
            model_name='sus',
            name='q9',
            field=models.FloatField(default=3, verbose_name='من احساس اطمینان می کنم از اینکه این سیستم را استفاده می کنم'),
        ),
        migrations.AddField(
            model_name='sus',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
